### ISSUE TITLE
Broken Card Scripts

### ISSUE THREAD

**Issue by CDGCodes** [Secuter/SecuterYGOCustomCards#11]
Hi there! Real big fan of your work here
My friends and I have been using your cards and we've had a real blast with them
But we have come across some issues

Rascal Ace Mech-Overload
- Doesn't return to the board at the end of the opponent's turn

Instant Armor
- Doesn't allow the monster to gain ATK through its Armor effect

Crearmor Destructive Sunshine
- Its Armor effect allows you to Special Summon Armor Spells/Traps (they have no Level and 0 ATK/DEF, with no way to increase this even with card effects)

Heart of the Primeval Forest
- Doesn't trigger when destroyed despite a valid target (we used Walking Tree of the Primeval Forest) existing in grave

**Comment by Secuter** [comment]
Thank you for the feedback and for reporting these bugs.
I'm looking into them.

**Comment by Secuter** [comment]
Hi, I fixed these errors

**Comment by CDGCodes** [comment]
Awesome. Should I leave this open to report new errors, or would you prefer me to make a new issue for them?

**Comment by Secuter** [comment]
> Awesome. Should I leave this open to report new errors, or would you prefer me to make a new issue for them?

Hi, I'd prefer to close it if you don't have any other errors to report right now.
If you find more errors, feel free to open another one.
Thanks
